// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBultewoGNQRl1aX1SumuHg-jXwL9D6xoc',
    appId: '1:201585737993:web:2fa84229d5fa90c85913d8',
    messagingSenderId: '201585737993',
    projectId: 'sample-notification-300d2',
    authDomain: 'sample-notification-300d2.firebaseapp.com',
    storageBucket: 'sample-notification-300d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdS-Bu_RsSpGsQmRnw4CSttsG_KjJlcHU',
    appId: '1:201585737993:android:265d3fdbbaafc5775913d8',
    messagingSenderId: '201585737993',
    projectId: 'sample-notification-300d2',
    storageBucket: 'sample-notification-300d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd9rn7lpN90J0W68sQro4IvOcjUfdIbCY',
    appId: '1:201585737993:ios:3ab45212179027335913d8',
    messagingSenderId: '201585737993',
    projectId: 'sample-notification-300d2',
    storageBucket: 'sample-notification-300d2.firebasestorage.app',
    iosBundleId: 'com.example.sampleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd9rn7lpN90J0W68sQro4IvOcjUfdIbCY',
    appId: '1:201585737993:ios:3ab45212179027335913d8',
    messagingSenderId: '201585737993',
    projectId: 'sample-notification-300d2',
    storageBucket: 'sample-notification-300d2.firebasestorage.app',
    iosBundleId: 'com.example.sampleProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBultewoGNQRl1aX1SumuHg-jXwL9D6xoc',
    appId: '1:201585737993:web:ae466ab0835ce2665913d8',
    messagingSenderId: '201585737993',
    projectId: 'sample-notification-300d2',
    authDomain: 'sample-notification-300d2.firebaseapp.com',
    storageBucket: 'sample-notification-300d2.firebasestorage.app',
  );

}