// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvPrQ-tjoWvq3N1kwhqDHWRBMBpClf0A',
    appId: '1:222652963588:web:c92d967f3ddc9fe1454e51',
    messagingSenderId: '222652963588',
    projectId: 'corekit-sdk-99a43',
    authDomain: 'corekit-sdk-99a43.firebaseapp.com',
    storageBucket: 'corekit-sdk-99a43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEPk8GC8-HiXyOMt9uRgH7S-VPvQ733-w',
    appId: '1:222652963588:android:df44307667e8a5b3454e51',
    messagingSenderId: '222652963588',
    projectId: 'corekit-sdk-99a43',
    storageBucket: 'corekit-sdk-99a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgSXA-GdWCvxh33cNEq1-v3OgIIMnps8U',
    appId: '1:222652963588:ios:6270dd3b290c7aa9454e51',
    messagingSenderId: '222652963588',
    projectId: 'corekit-sdk-99a43',
    storageBucket: 'corekit-sdk-99a43.firebasestorage.app',
    iosBundleId: 'com.corekit.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgSXA-GdWCvxh33cNEq1-v3OgIIMnps8U',
    appId: '1:222652963588:ios:6270dd3b290c7aa9454e51',
    messagingSenderId: '222652963588',
    projectId: 'corekit-sdk-99a43',
    storageBucket: 'corekit-sdk-99a43.firebasestorage.app',
    iosBundleId: 'com.corekit.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsvPrQ-tjoWvq3N1kwhqDHWRBMBpClf0A',
    appId: '1:222652963588:web:5cb30da203fd5f4a454e51',
    messagingSenderId: '222652963588',
    projectId: 'corekit-sdk-99a43',
    authDomain: 'corekit-sdk-99a43.firebaseapp.com',
    storageBucket: 'corekit-sdk-99a43.firebasestorage.app',
  );

}