// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLX22iZ-Z8vrWurl2RSYzPwcaUmKm2Ccg',
    appId: '1:286967535054:web:781a0fbabe6dfff18a079f',
    messagingSenderId: '286967535054',
    projectId: 'corekit-sdk',
    authDomain: 'corekit-sdk.firebaseapp.com',
    storageBucket: 'corekit-sdk.firebasestorage.app',
    measurementId: 'G-S19WN4N1PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKOpEDonGMv6AG8UVjc1xlP1Sy2bLxekk',
    appId: '1:286967535054:android:89ca18c67ffb49b28a079f',
    messagingSenderId: '286967535054',
    projectId: 'corekit-sdk',
    storageBucket: 'corekit-sdk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeOZTSvdRIqt51sNg6WQBriFbMsD8OC2s',
    appId: '1:286967535054:ios:6aa1b0a861188e718a079f',
    messagingSenderId: '286967535054',
    projectId: 'corekit-sdk',
    storageBucket: 'corekit-sdk.firebasestorage.app',
    iosBundleId: 'com.example.corekitSdk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeOZTSvdRIqt51sNg6WQBriFbMsD8OC2s',
    appId: '1:286967535054:ios:6aa1b0a861188e718a079f',
    messagingSenderId: '286967535054',
    projectId: 'corekit-sdk',
    storageBucket: 'corekit-sdk.firebasestorage.app',
    iosBundleId: 'com.example.corekitSdk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLX22iZ-Z8vrWurl2RSYzPwcaUmKm2Ccg',
    appId: '1:286967535054:web:c055050e20c4c7f78a079f',
    messagingSenderId: '286967535054',
    projectId: 'corekit-sdk',
    authDomain: 'corekit-sdk.firebaseapp.com',
    storageBucket: 'corekit-sdk.firebasestorage.app',
    measurementId: 'G-0ERFDQB71Z',
  );

}